# Generated by Django 5.2.6 on 2026-02-10 02:56

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Material",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "code",
                    models.CharField(
                        max_length=50,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator("^\\d+$", "O código deve conter apenas números.")
                        ],
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="EntryInvoiceQueue",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("provider", models.CharField(max_length=255)),
                ("close_popup", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendente"),
                            ("processing", "Processando"),
                            ("cancelled", "Cancelada"),
                            ("done", "Transmitida"),
                        ],
                        default="pending",
                        max_length=50,
                    ),
                ),
                ("invoice_path", models.CharField(blank=True, max_length=255, null=True)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ExitInvoiceQueue",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("provider", models.CharField(max_length=255)),
                ("close_popup", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendente"),
                            ("processing", "Processando"),
                            ("cancelled", "Cancelada"),
                            ("done", "Transmitida"),
                        ],
                        default="pending",
                        max_length=50,
                    ),
                ),
                ("invoice_path", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "freight",
                    models.CharField(
                        choices=[
                            ("0", "Contratado p/ conta Remetente (CIF)"),
                            ("1", "Contratado p/ conta Destinatário (FOB)"),
                            ("2", "Contratado p/ conta Terceiros"),
                            ("3", "Próprio p/ conta Remetente"),
                            ("4", "Próprio p/ conta Destinatário"),
                            ("9", "Sem Frete"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "search_carrier_by",
                    models.CharField(choices=[("code", "Código"), ("name", "Nome")], default="code", max_length=50),
                ),
                ("carrier_name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "carrier_code",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator("^\\d+$", "O código deve conter apenas números.")
                        ],
                    ),
                ),
                ("observation", models.CharField(max_length=500)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="InvoiceItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("object_id", models.PositiveIntegerField()),
                ("material_quantity", models.FloatField()),
                ("material_price", models.FloatField()),
                ("discount", models.FloatField(default=0.0)),
                (
                    "content_type",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="contenttypes.contenttype"),
                ),
                (
                    "material",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="invoices_automation.material"),
                ),
            ],
        ),
    ]
