# Generated by Django 5.2.6 on 2026-07-18 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoices_automation", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="entryinvoicequeue",
            name="which_filial",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Selecione a Filial (Opcional)"),
                    ("bahia", "Bahia"),
                    ("rj", "Rio de Janeiro"),
                    ("mt", "Mato Grosso"),
                    ("varejo", "Varejo"),
                    ("jba", "JBA"),
                ],
                default="",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="exitinvoicequeue",
            name="which_filial",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Selecione a Filial (Opcional)"),
                    ("bahia", "Bahia"),
                    ("rj", "Rio de Janeiro"),
                    ("mt", "Mato Grosso"),
                    ("varejo", "Varejo"),
                    ("jba", "JBA"),
                ],
                default="",
                max_length=50,
            ),
        ),
    ]
